name: PR test & lint
run-name: ${{ github.actor }} is running Test & Lint on PR 🚀
on:
    pull_request:
        types: [opened, synchronize, edited]
        branches:
            - "main"
jobs:
    validate:
        name: "Run lint & testing on PR"
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [24.x]
        steps:
            - name: Init - Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v6
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Source - checkout
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            - name: Source - npm install
              run: npm ci

            - name: Source - knip
              run: npm run knip --if-present

            - name: Source - format:check --if-present
              run: npm run format:check --if-present

            - name: Source - lint --if-present
              run: npm run lint --if-present

            - name: Source - build --if-present
              run: npm run build --if-present

            - name: Source - lint package
              run: npx -y publint

            - name: Source - build storybook --if-present
              run: npm run build-storybook --if-present
