name: CI - Production Release

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  # Create npm package
  package:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm run build
      - run: npm publish --access=public --allow-same-version --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
